spring.application.name=qb-integration-service
# Base de datos
spring.datasource.url=jdbc:mariadb://localhost:3306/qb_integration_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

# Puerto del servidor
server.port=8080

logging.level.org.apache.cxf=DEBUG
logging.level.org.apache.cxf.interceptor=INFO
logging.level.com.sun.xml.ws=TRACE
logging.level.org.apache.cxf.jaxb=DEBUG

# Base de datos secundaria - Sistema de tickets (wordpress_db)
wordpress.datasource.url=jdbc:mariadb://localhost:3307/wordpress_db
wordpress.datasource.username=user
wordpress.datasource.password=${WORDPRESS_DB_PASSWORD}
wordpress.datasource.driver-class-name=org.mariadb.jdbc.Driver